enable-magisk-update = true
parallel-jobs = 1

cli-source = "inotia00/revanced-cli"
patches-source = "inotia00/revanced-patches"

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
dpi = "120-640dpi"

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
build-mode = "module"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube'"

[YouTube-Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
build-mode = "module"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"
